import type { Article } from './types';

const article: Article = {
  slug: 'human-employment-ai-era',
  title: 'Human Employment: The Next Frontier of Responsible Investing in the AI Era',
  excerpt:
    'As AI transforms industries, responsible investing must evolve to include a commitment to sustaining human employment, not as nostalgia, but as a strategic imperative for long-term value creation.',
  content: `
      <h2><strong>Human Employment: The Next Frontier of Responsible Investing in the AI Era</strong></h2>

      <p>In mid-2025, Swedish fintech firm Klarna did something few tech companies do: it publicly reversed a bold automation bet. After touting the replacement of 700 customer-service employees with artificial intelligence, Klarna faced plummeting satisfaction and mounting user complaints. The CEO admitted they had "gone too far" and rushed to rehire humans to restore service quality. This dramatic U-turn underscores a new reality for businesses and investors alike: in the rush to maximize efficiency with AI, companies risk eroding long-term value, stakeholder trust, and even operational effectiveness. As artificial intelligence transforms industries, responsible investing must evolve to include a deliberate commitment to sustaining human employment, not as a nostalgic nod to the past, but as a strategic imperative for the future.</p>

      <h3><strong>The Efficiency Dilemma: AI's Social Cost</strong></h3>

      <p>Across sectors and regions, AI adoption is accelerating. From automated customer support chatbots to algorithmic decision systems, companies are seizing AI's promise of lower costs and higher productivity. But this pursuit of efficiency comes with a hidden social cost: the displacement of human workers on a potentially massive scale. The World Economic Forum's latest survey of 803 companies found employers expect to eliminate 83 million jobs by 2027 even as they create 69 million new ones, resulting in a net loss of 14 million jobs globally. That amounts to 2% of current employment wiped out in just five years, largely due to technology adoption. Other estimates paint an even starker picture: one IMF analysis suggests nearly 40% of jobs worldwide are exposed to AI-driven transformation, with roughly half of those tasks potentially taken over by machines. Unlike past waves of automation that mainly affected routine work, this AI wave is encroaching on higher-skill white-collar roles as well.</p>

      <p>The macroeconomic risks of this "dehumanized" value creation are significant. If tens of millions of people lose livelihoods, who will buy the products and services that fuel corporate profits? A shrinking labor share of income and rising inequality can dampen consumer demand and destabilize economies. Indeed, the International Monetary Fund warns that unchecked AI adoption could deepen income inequality and stoke social unrest. Productivity gains will disproportionately reward high-skilled workers and capital owners, while many others fall behind, worsening polarization. Without proactive strategies, from social safety nets to retraining programs, the AI revolution could undermine broad-based prosperity and threaten the social cohesion on which markets depend. In short, an economy that sidelines human workers risks undermining itself in the long run.</p>

      <h3><strong>ESG's Blind Spot: AI and the "S" Factor</strong></h3>

      <p>The Environmental, Social, and Governance (ESG) movement has, to date, struggled to fully account for this looming social challenge. Current ESG frameworks tend to focus heavily on environmental issues (like carbon emissions) and governance concerns (like board independence or data privacy). The "S" (social) pillar does cover labor practices and human capital, but AI's impact on employment remains a blind spot in many ESG metrics. For example, the new European Sustainability Reporting Standards (ESRS) under the EU's Corporate Sustainability Reporting Directive list dozens of disclosure topics, yet "artificial intelligence" is not explicitly required as a standalone issue. That doesn't mean AI's workforce impacts can be ignored:under these standards, any topic that significantly affects people or the environment can be deemed material. And clearly, if a company's deployment of AI leads to widespread layoffs or labor unrest, it crosses that materiality threshold by triggering stakeholder concern, reputational risk, and even compliance issues. Still, the absence of explicit AI-centric metrics in ESG reporting means many companies don't yet report how automation is affecting their employees.</p>

      <p>This gap is starting to draw scrutiny. Major ESG analysts and investors are debating whether to fold AI impacts into existing categories or create new metrics altogether. They recognize that labor displacement, algorithmic bias, and other AI-driven social risks don't fit neatly into traditional checklists. For instance, ESG rating agencies have long evaluated human capital management:tracking metrics like employee turnover, training hours, or diversity. But few, if any, ratings currently penalize a firm for aggressive automation or reward one for retaining workers. The result is that a company could boast a high ESG score for its low carbon footprint and charitable programs, even as it quietly replaces thousands of employees with machines. This imbalance reflects an outdated view of "social responsibility."</p>

      <p>To be fair, the social pillar of ESG does provide a foundation. It typically encompasses "labor practices, human rights, community engagement, diversity and inclusion, and employee well-being." A company that mistreats its workers or devastates a community with layoffs can certainly face social score downgrades. And make no mistake: AI is poised to become a major labor practice issue. As a Georgetown Law review noted, "a major social implication of AI is its potential to eliminate jobs." If ESG investing is about long-term, sustainable value creation, then the fate of employees in the AI era must become a core concern. The question is whether investors and standards-setters will explicitly integrate this concern, or continue treating it as an afterthought.</p>

      <h3><strong>Stakeholder Capitalism and AI</strong></h3>

      <p>This debate cuts to the heart of stakeholder capitalism, the idea that companies exist to serve not just shareholders, but all stakeholders, including employees. In 2019, over 180 CEOs of America's largest companies signed the Business Roundtable's Statement on the Purpose of a Corporation, pledging to "invest in our employees" by compensating them fairly, providing training and education for a rapidly changing world, and treating them with dignity and respect. That marked a watershed acknowledgment that employees are central to a company's mission and long-term success. But as AI gains steam, that noble statement is facing its biggest test. Will corporations honor the spirit of investing in their people, even when algorithms might cut costs faster? Or will the commitment to stakeholders prove hollow if it conflicts with short-term profits?</p>

      <p>Legally, nothing forces companies to maintain a certain level of human employment:boards still have wide latitude to prioritize profits. In fact, under U.S. law, executives can argue that even decisions benefiting stakeholders (like workers) are permissible if they "have a rational relationship to the best interests of stockholders." In other words, if keeping more humans on the payroll is believed to protect long-term shareholder value:say, by avoiding reputational damage:the business judgment rule supports it. This is a critical point: enlightened leaders can choose a human-centric strategy on solid business grounds. One could argue, as that Georgetown analysis does, that using AI to eliminate large numbers of jobs poses a reputational risk significant enough to harm a company's value, thus warranting restraint in workforce cuts. In practice, of course, many companies still default to layoffs despite the reputational risks, especially if no law prohibits it.</p>

      <p>This is precisely why "responsible AI" needs to include responsibility to employees. Companies that are serious about ESG and stakeholder principles should be crafting explicit policies for how they implement automation. This might include commitments to retrain or redeploy workers whose jobs are affected by AI, transparent communication about technological changes, and ethical guidelines on where to augment human labor instead of replace it. Thus far, only a handful of firms have openly adopted such policies. But the momentum is building.</p>

      <h3><strong>Investors on Alert: AI as a Social Risk</strong></h3>

      <p>In the investment community, we are already seeing early signs of this shift. A year ago, many ESG funds were heavily weighted in Big Tech stocks, partly because those firms offered high returns with relatively low direct emissions (a boon for the E pillar). But now ESG fund managers are growing anxious about their tech exposure as AI's risks come into focus. According to Bloomberg, some managers worry about an "AI blowback":a scenario where an unforeseen AI-related incident triggers a market downturn. While sci-fi disasters grab headlines (like rogue algorithms in fighter jets), more immediate for investors are the social and governance red flags: mass layoffs, workforce destabilization, or public backlash against companies seen as over-automating.</p>

      <p>In fact, leading institutional investors have begun pressing companies on these very issues. The $1.4 trillion Norwegian sovereign wealth fund recently told corporate boards to take the "severe and uncharted" risks of AI seriously. The New York City pension system, with $248 billion in assets, said it is "actively monitoring" how portfolio companies use AI. Generation Investment Management, the sustainable fund co-founded by Al Gore, has ramped up research into generative AI's impacts and is talking daily with investee companies about the attendant risks and opportunities. Perhaps most striking is the stance of labor-affiliated investors: the AFL-CIO's $12 billion Equity Index Fund filed shareholder proposals asking firms to disclose whether they have guidelines to protect workers, customers and the public from AI harms. These proposals explicitly cite concerns ranging from algorithmic discrimination to "mass layoffs resulting from automation." In other words, a major institutional investor is warning that if you fire lots of people in the name of AI, expect scrutiny.</p>

      <p>Transparency is the first demand. As one ESG analyst at BNP Paribas noted, there's currently "no methodology to quantify" AI social risk:so her team simply started asking companies how many jobs they expect to cut due to AI like ChatGPT. So far, "I haven't seen one company that can give me a useful number," she says. This lack of preparedness should concern boards. If companies have not evaluated the workforce implications of their AI strategies, investors may see that as a governance failure. Conversely, firms that do have a plan:say, a robust retraining program or a commitment to limit involuntary layoffs:could find themselves rewarded with patient capital from ESG funds looking to reduce social risk.</p>

      <p>The writing on the wall is clear: investors are beginning to treat AI's impact on jobs as a material ESG issue, not just a tech trend. This mirrors the broader evolution of ESG over recent years:from climate change to #MeToo to data privacy, stakeholder pressures have a way of rapidly redefining the "musts" of corporate responsibility. Human employment in the age of AI looks poised to be the next such frontier. Responsible investing will, by necessity, expand its lens to ask: How is this company balancing technological innovation with its duty to workers and communities?</p>

      <h3><strong>When Automation Overreaches: Reputational and Strategic Risks</strong></h3>

      <p>The cautionary tale of Klarna cited earlier is far from unique. We've seen high-profile examples of over-automation backfiring both operationally and reputationally. In the customer service realm alone, multiple companies that rushed to replace staff with AI have quickly encountered the limits of a machine-only approach. Last year, an Indian tech CEO proudly announced on social media that he had laid off 90% of his support team in favor of an AI chatbot:only to face fierce public backlash for his tone-deaf celebration of job cuts. In aviation, Germany's Lufthansa revealed it would slash 4,000 jobs citing increased use of AI, only to receive criticism about deteriorating service quality. Even within the tech giants, there is recognition that unbridled automation can be a mistake. Tesla's CEO Elon Musk, after trying to heavily automate production, famously confessed, "Excessive automation at Tesla was a mistake… Humans are underrated." His admission came after Tesla's Model 3 assembly line became snarled by an overly complex web of robots, forcing the company to reintroduce more human flexibility into the process.</p>

      <p>These examples illustrate two key points. First, the human touch often remains essential for quality, innovation, and resilience. Klarna's AI customer-service bots could not match human agents in handling nuanced or emotionally charged inquiries, leading to frustrated customers and damage to the brand. Tesla's robotic factory couldn't adapt to unforeseen hiccups the way human workers could, resulting in production delays. The lesson is that humans and AI together can outperform AI alone in many complex contexts:a fact companies ignore at their peril.</p>

      <p>Second, there is a growing reputational risk in being seen as a company that mindlessly slashes humans for machines. In an era of social media, layoffs attributed to "AI efficiency" can generate public relations nightmares, not to mention distrust among remaining employees and local communities. Companies prizing their brand equity should think twice before boasting about automation-driven firings. When one software firm's executive casually noted that AI could let them cut 7% of their workforce, it not only rattled staff morale but also drew negative media attention. Contrast that with companies that have taken a more people-centric narrative: some leaders have explicitly stated they will use AI to empower their teams, not eliminate them. For example, the CEO of language app Duolingo recently clarified that their aggressive AI push is "about mindset, not mass layoffs," retooling employee roles rather than removing people. That approach won praise as a model for balancing innovation with responsibility.</p>

      <p>Beyond perception, over-automation can pose strategic business risks. Cutting too deep into the workforce in pursuit of short-term cost savings may hollow out an organization's institutional knowledge and creative capacity:the very ingredients for long-term competitiveness. A stark data point underscores this: an MIT Media Lab study found that 95% of corporate AI initiatives have so far generated no tangible return on investment. This suggests that many firms might be leaping into AI without a clear payoff, potentially laying off employees for efficiency gains that never fully materialize. If the promised productivity boost doesn't pan out, companies could find themselves weakened:having lost human talent and wasted capital on unproven tech. The smarter play is to pilot AI carefully while preserving the human capital that can adapt and leverage new tools.</p>

      <h3><strong>The Competitive Edge of a Human-Centric Strategy</strong></h3>

      <p>Far from being a drag on profits, designing businesses that prioritize human participation:even in high-tech environments:can be a source of competitive advantage. Think of it as "augmented intelligence" instead of artificial intelligence: companies that figure out how to combine the speed of AI with the creativity, empathy, and critical thinking of humans are likely to outperform in innovation and customer loyalty. There's evidence, for instance, that firms with high employee satisfaction and engagement (a proxy for treating workers well) tend to outperform the broader market over time. This aligns with the ethos of stakeholder capitalism, which posits that investing in your workers yields returns in productivity and stability.</p>

      <p>Leading organizations have already internalized this. Some of the world's biggest employers are pouring resources into upskilling and reskilling their people, explicitly to meet the tech future with a capable human workforce rather than a shrunken one. Telecom giant AT&T invested $1 billion in a "Future Ready" retraining program to equip a large chunk of its workforce with skills in cybersecurity, software engineering, data science and more. The goal was to transform AT&T's talent for the digital age without mass layoffs. Likewise, Amazon launched an Upskilling 2025 initiative, committing hundreds of millions of dollars to train employees for higher-tech roles within the company. These programs are not philanthropy; they are strategic moves to ensure the company has the human skills needed as technology evolves. By redeploying workers instead of firing them, companies maintain morale, save on the costs of turnover, and create a culture of loyalty and continuous learning.</p>

      <p>Another competitive benefit of sustaining employment is resilience. The past few years have taught businesses the importance of adaptability amid shocks:whether a pandemic, supply chain disruptions, or rapid technological shifts. A workforce that is experienced, cross-trained, and committed can pivot far faster and more effectively than one that's been minimized to a skeleton crew. For example, when unexpected events occur or AI systems fail, having knowledgeable humans in the loop can be the difference between a minor hiccup and a major catastrophe. This resilience is a material asset. It's telling that Klarna, after its automation misstep, cited restoring "trust, service quality, and brand reputation" as reasons for re-emphasizing human staff. The company learned the hard way that human judgement and empathy were competitive differentiators in customer experience:ones that no algorithm could fully replicate.</p>

      <p>Finally, sustaining employment at scale supports the broader economic ecosystem in which businesses operate. Companies that choose to retain and retrain workers contribute to social stability and consumer confidence. Their employees, drawing paychecks, continue to spend in the economy, fueling demand for goods and services (including those that tech firms produce). This virtuous cycle shouldn't be underestimated. As IMF Managing Director Kristalina Georgieva noted, we need policies and business practices that harness AI's potential while raising incomes around the world:the win-win scenario. If instead AI is used narrowly to cut labor costs, we risk a world of higher corporate profits but lower aggregate demand, as fewer people have good jobs. Savvy investors understand that scenario is unsustainable. Truly "sustainable" value creation must mean prosperity is widely shared, not concentrated in the hands of a few ultra-efficient tech platforms. In this sense, keeping more people in productive employment is not just a feel-good goal:it's linked to the long-term growth prospects of the economy and the health of markets.</p>

      <h3><strong>Toward a New Paradigm: Human-Centered ESG in the AI Age</strong></h3>

      <p>All of this points to an emerging paradigm for responsible investing and corporate strategy. The next evolution of ESG will likely see explicit recognition of workforce sustainability as key to long-term resilience. We can envision ESG rating frameworks beginning to include metrics such as: the percentage of employees retrained or redeployed due to automation, the ratio of AI investments to human capital investments, employee retention rates during tech transitions, or even qualitative disclosures on how companies govern the use of AI vis-à-vis their workforce. Notably, the World Economic Forum's Stakeholder Capitalism Metrics already encourage disclosure of "employment and wealth generation" figures under the "Prosperity" theme. Those metrics push companies to report not just how many people they employ, but how their business model contributes to quality jobs and economic inclusion. This aligns perfectly with the idea that sustaining and creating good jobs is part and parcel of running a sustainable business.</p>

      <p>Policy is moving in this direction too. While hard regulations explicitly linking AI and employment are still nascent, the signs of a regulatory shift are visible on the horizon. In addition to AI ethics rules (like the EU AI Act's restrictions on certain harmful uses), policymakers are mulling ways to blunt the social downsides of automation. Ideas like a "robot tax":essentially a tax on companies that automate away jobs, to fund worker retraining:have been floated by tech leaders and even piloted in some regions. Governments are also considering requirements for companies to perform impact assessments on how major tech deployments will affect jobs, similar to environmental impact assessments for new projects. It is conceivable that within a few years, large firms could be asked by regulators or stock exchanges to disclose how many jobs were lost or created due to AI adoption, and what is being done to support affected workers. Early movers on this front will have the advantage of shaping the narrative rather than reacting to it.</p>

      <p>For companies and investors, therefore, the opportunity is clear. Those who proactively embrace a human-centric approach to AI can differentiate themselves as true sustainability leaders. They can attract capital from the growing pool of ESG-oriented funds that are becoming wary of automation risks. They can build stronger relationships with stakeholders:not just employees, but also consumers, regulators, and communities:who increasingly favor businesses that balance profit with purpose. And they can foster innovation by leveraging AI as a tool to amplify human creativity, rather than a blunt instrument to prune headcount.</p>

      <p>In practical terms, this might mean deploying AI in ways that complement and elevate human roles:for example, using AI to handle repetitive tasks so employees can focus on creative, strategic, or relationship-based work. It also means investing in people so they can effectively work alongside AI. The World Economic Forum notes that 42% of companies plan to train workers in AI and big data skills over the next five years. This is a positive trend: it treats employees as assets to be upgraded, not costs to be cut. As Saadia Zahidi of the WEF put it, after years of turmoil there is a "clear way forward to ensure resilience":by making sure individuals are at the heart of the future of work through education, reskilling, and support. In other words, put humans at the heart of the future of work.</p>

      <h3><strong>Conclusion: Redefining "Efficiency" and "Responsibility"</strong></h3>

      <p>The drive for efficiency has long been a core tenet of business. But efficiency cannot be measured by cost savings alone. In the age of AI, we must broaden the definition to include social efficiency: the idea that a well-functioning, sustainable enterprise optimizes not just for immediate profit, but for the well-being of the humans who make economies function. Responsible investing, similarly, must update its playbook. Just as it became untenable for an ESG fund to ignore a company's carbon footprint or workforce diversity, it will become unacceptable to ignore how a company navigates the AI revolution's impact on jobs. Sustaining human employment is not a quaint, Luddite goal; it is integral to sustaining demand, social stability, and the human capital that drives innovation.</p>

      <p>We stand at a crossroads. Down one path lies a future of automated efficiency at all costs:a future of impressive short-term margins perhaps, but also one of alienated workers, angry publics, and fragile markets prone to "AI blowback." Down the other path lies a more deliberate, human-centered approach:where technology and people grow together, where companies find competitive edges in empathy and expertise, and where investors reap steady returns from a healthier, more inclusive economy. The choice should be clear. Prioritizing human participation in an increasingly high-tech world is not just an ESG nicety; it is emerging as a core driver of long-term value. Responsible investors and corporate leaders who recognize this now:who champion the human in the loop:will help forge an AI-powered economy that works for all stakeholders. In doing so, they will redefine "responsible investing" for the coming era, proving that sustainability and innovation are not at odds but mutually reinforcing. The companies that prosper in 2030 and beyond may well be those that had the foresight and courage today to say: Efficiency is important, but people are indispensable.</p>
    `,
  author: 'Leo Meggitt',
  date: '15 January 2026',
  readTime: '15 min read',
  image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=2070',
  category: 'ESG & Strategy',
};

export default article;
